include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - control_flow_in_finally
    - empty_statements
    - no_duplicate_case_values
    - always_declare_return_types
    - empty_catches
    - use_super_parameters
    - directives_ordering
