name: gardeny
description: This is a project to share description of plants, gamification, location and more.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  widgetbook: ^2.4.1
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
   - family: Nunito
     fonts:
       - asset: assets/fonts/nunito/Nunito-Light.ttf
       - asset: assets/fonts/nunito/Nunito-Regular.ttf
       - asset: assets/fonts/nunito/Nunito-Medium.ttf
       - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
   - family: Arima Madurai
     fonts:
       - asset: assets/fonts/arima-madurai/ArimaMadurai-Regular.ttf
       - asset: assets/fonts/arima-madurai/ArimaMadurai-Medium.ttf
       - asset: assets/fonts/arima-madurai/ArimaMadurai-Bold.ttf
       - asset: assets/fonts/arima-madurai/ArimaMadurai-ExtraBold.ttf
